### ISSUE TITLE
Standardize on Tabs or Spaces for your XML files

### ISSUE THREAD

**Issue by XavierBalderdash** [Oeathus/AAFDayZ#2]
![tab_spaces](https://github.com/Oeathus/AAFDayZ/assets/117959604/22e93e36-950d-44f1-ad6e-9c68cd8d90b5)

https://stackoverflow.com/questions/30140595/show-whitespace-characters-in-visual-studio-code

You should show tabs and spaces, it'll help with checking alignment between XML files on different lines. If these aren't evenly aligned, they can break the whole file.

**Comment by Oeathus** [comment]
Good call, I had gotten used to Jetbrains converting everything for me as I typed, I have to set my vscode up to do the same, gonna take a little geting used to lol

**Comment by Oeathus** [comment]
I've found a pre-commit setup from Lucas-C to standardize the indents, it currently will set all tabs to 4 spaces, I believe that should bring most files into correct alignment.
