### ISSUE TITLE
Move Damage in container.spawnable.xml to top of the file

### ISSUE THREAD

**Issue by XavierBalderdash** [Oeathus/AAFDayZ#3]
You could shorten up the file by changing a few things:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<spawnabletypes>
    <damage min="0.30" max="0.75" />

	<type name="Bear_Beige">
		<damage min="0.3" max="0.7" />
		<cargo chance="0.00">
			<item name="Paper" chance="0.50" />
			<item name="Rag" chance="0.50" />
		</cargo>
	</type>
```

If you change Line #3 to `<damage min="0.30" max="0.7" />`, you can remove every instance of `<damage min="0.3" max="0.7" />` under the items (bear_beige in the case of the first item in the file.)

The only object you _don't_ have damage on in this file is the AmmoBox, which will inherit the top damage configuration. If you want the ammo box to ignore the `<damage min="0.3" max="0.7" />`, assign it a specific range, and let everything else inherit the damage value from the top of the file.

**Comment by Oeathus** [comment]
Good Catch!! I was getting a little burned out splitting the files and hurried through the spawnables. I've refactored this file and will look for more optimizations like this, Thank you!
